# Generated by Django 4.0.6 on 2022-08-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_instahp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='instahp',
            name='comments',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instahp',
            name='like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
